---
- hosts: all
  become: yes
  vars_files:
    - roles/linux/defaults/main.yml
    - roles/api/defaults/main.yml
    - environments/{{env}}.yml
    - environments/{{env}}-secrets.yml
  roles:
    - common
    - messaging
