---
- hosts: all
  become: yes
  vars_files:
    - roles/linux/defaults/main.yml
    - roles/api/defaults/main.yml
    - roles/apps/defaults/main.yml
    - roles/sandbox-manager-api/defaults/main.yml
    - roles/sandbox-manager/defaults/main.yml
    - roles/apacheds/defaults/main.yml
    - roles/pwm/defaults/main.yml
    - environments/{{env}}.yml
    - environments/{{env}}-secrets.yml
  roles:
    - common
    - auth
