---
installer_user: "vagrant"
services_host: "localhost"
use_secure_http: false
use_custom_ssl_certificates: false
custom_ssl_certificates_path: "/home/{{installer_user}}/certificates"
my_aws_output_format: "json"
my_enable_backup_restore_jobs: false
my_enable_aws_snapshot: false
enable_pwm: false
mysql_host: "localhost"
hspc_artifact_repo: "https://nexus.hspconsortium.org/repository/maven-all"
enable_account: false
enable_account_api: false
email_account_description: "SMART Account Services"
email_smtp_port: "587"
email_admin_address: "admin@example.com"
email_contact_addresss: "contact@example.com"
#account_server_external_url: "{{pwm_server_external_url}}"
apacheds_server_external_host: "{{services_host}}"
apacheds_server_installer_enabled: true
pwm_server_external_host: "{{services_host}}"
pwm_server_external_port: "9092"
pwm_unlocked: true
pwm_sso_authentication_header_name: "changeme"
patient_picker_project_version: "1.2.1"
patient_picker_server_external_host: "{{services_host}}"
patient_picker_server_external_port: "9094"
auth_server_artifact_version: "1.9.10"
auth_server_artifact_repository_url: "{{release_repository_url}}"
auth_server_external_host: "{{services_host}}"
auth_server_external_port: "9060"
auth_server_initial_memory: "64M"
auth_server_max_memory: "128M"
auth_server_persona_cookie_domain: "localhost"
auth_server_CONTEXT_FHIR_ENDPOINT: "{{api_dstu2_server_external_url}},{{mock_api_dstu2_server_external_url}},{{api_stu3_server_external_url}},{{mock_api_stu3_server_external_url}}"
auth_mysql_database_drop: true
auth_server_spring_profiles: "production,users-ldap"
#auth_server_newUserUrl: "{{pwm_server_external_url}}public/newuser"
#auth_server_forgotPasswordUrl: "{{pwm_server_external_url}}public/forgottenpassword"
api_server_artifact_version: "1.8.0"
api_server_artifact_repository_url: "{{release_repository_url}}"
enable_api_sample_data: true
enable_mock_endpoints: false
#api_server_oauth2_clientId: "hspc_resource_server"
api_mysql_host: "{{mysql_host}}"
api_mysql_username: "{{mysql_username}}"
api_mysql_password: "{{mysql_password}}"
api_mysql_reset: true
api_dstu2_server_enabled: true
api_dstu2_server_external_host: "{{services_host}}"
api_dstu2_server_external_port: "9071"
api_dstu2_mysql_database_drop: true
#api_dstu2_mysql_reset_database: true
#api_dstu2_server_initial_memory: "128M"
api_dstu2_server_initial_memory: "256M"
api_dstu2_server_max_memory: "256M"
api_dstu2_sample_patients_limit: "20"
mock_api_dstu2_server_external_host: "{{services_host}}"
mock_api_dstu2_server_external_port: "9271"
mock_api_dstu2_server_initial_memory: "128M"
mock_api_dstu2_server_max_memory: "256M"
api_stu3_v2_server_enabled: false
api_stu3_v2_server_external_host: "{{services_host}}"
api_stu3_v2_server_external_port: "9072"
api_stu3_v2_mysql_database_drop: true
api_stu3_v2_server_initial_memory: "256M"
api_stu3_v2_server_max_memory: "256M"
api_stu3_v3_server_enabled: false
api_stu3_v3_server_external_host: "{{services_host}}"
api_stu3_v3_server_external_port: "9073"
api_stu3_v3_mysql_database_drop: true
api_stu3_v3_server_initial_memory: "256M"
api_stu3_v3_server_max_memory: "256M"
api_stu3_server_enabled: true
api_stu3_server_external_host: "{{services_host}}"
api_stu3_server_external_port: "9074"
api_stu3_mysql_database_drop: true
#api_stu3_server_initial_memory: "128M"
api_stu3_server_initial_memory: "256M"
api_stu3_server_max_memory: "256M"
api_stu3_sample_patients_limit: "20"
mock_api_stu3_server_external_host: "{{services_host}}"
mock_api_stu3_server_external_port: "9274"
mock_api_stu3_server_initial_memory: "128M"
mock_api_stu3_server_max_memory: "256M"
messaging_server_artifact_version: "1.4.0"
messaging_server_artifact_repository_url: "{{release_repository_url}}"
messaging_server_external_host: "{{services_host}}"
messaging_server_external_port: "9091"
messaging_server_initial_memory: "32M"
messaging_server_max_memory: "64M"
messaging_profiles: "test"
sandman_server_artifact_version: "2.2.0"
sandman_server_artifact_repository_url: "{{release_repository_url}}"
sandman_server_external_host: "{{services_host}}"
sandman_server_external_port: "9080"
sandman_server_initial_memory: "32M"
sandman_server_max_memory: "128M"
sandman_server_send_email: false
sandman_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v4_url: "{{api_stu3_server_external_url}}"
sandman_api_server_artifact_version: "0.4.2"
sandman_api_server_artifact_repository_url: "{{release_repository_url}}"
sandman_api_server_external_host: "{{services_host}}"
sandman_api_server_external_port: "13000"
sandman_api_server_initial_memory: "128M"
sandman_api_server_max_memory: "256M"
sandman_api_server_send_email: "false"
sandman_api_mysql_database_drop: true
sandman_api_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_api_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v4_url: "{{api_stu3_server_external_url}}"
#gallery_server_external_url: "none"
#gallery_server_internal_port: "0"
bilirubin_risk_chart_project_version: "master"
bilirubin_risk_chart_server_external_host: "{{services_host}}"
bilirubin_risk_chart_server_external_port: "9086"
growth_chart_app_project_version: "0.1.3"
growth_chart_app_server_external_host: "{{services_host}}"
growth_chart_app_server_external_port: "9089"
bp_centiles_app_project_version: "v0.1.2"
bp_centiles_app_server_external_host: "{{services_host}}"
bp_centiles_app_server_external_port: "9081"
cardiac_risk_app_project_version: "v0.1.1"
cardiac_risk_app_server_external_host: "{{services_host}}"
cardiac_risk_app_server_external_port: "9082"
patient_data_manager_project_version: "1.0.3"
patient_data_manager_server_external_host: "{{services_host}}"
patient_data_manager_server_external_port: "9096"


#firebase_projectName: "none"
#firebase_projectId: "none"
#firebase_database_url: "none"
#apps_server_external_host: "{{services_host}}"
#apps_server_external_port: "9093"
#patient_picker_server_external_host: "{{apps_server_external_host}}"
#patient_picker_server_external_port: "{{apps_server_external_port}}"
