---
- name: "download jetty-runner"
  become_user: "{{hosting_username}}"
  maven_artifact:
    group_id: "org.eclipse.jetty"
    artifact_id: "jetty-runner"
    version: "9.3.6.v20151106"
    extension: "jar"
    repository_url: "{{release_repository_url}}"
    dest: "{{hosting_user_home}}/{{jetty_runner_artifact_artifact_id}}-{{jetty_runner_artifact_version}}.{{jetty_runner_artifact_packaging}}"

- name: "config jetty-runner"
  become_user: "{{hosting_username}}"
  copy: src=jetty.xml dest={{hosting_user_home}}/jetty.xml

- name: "Configure MySQL user"
  mysql_user: name={{mysql_username}} host={{mysql_connect_host}} password={{mysql_password}} priv={{mysql_privilage}} state=present

- name: "Drop anonymous MySQL user"
  mysql_user: name='' host={{mysql_connect_host}} state=absent

- name: "Update .bash_profile"
  lineinfile:
    path: "{{installer_user_home}}/.bash_profile"
    line: '{{item}}'
  with_items:
    - "export NGINX_HOME={{nginx_home}}"
    - "export NGINX_SITES=$NGINX_HOME/sites-enabled"
    - "export SERVICE_HOME=/etc/systemd/system"
    - "export EDITOR=vi"
    - "alias n='cd $NGINX_SITES'"
    - "alias s='cd $SERVICE_HOME'"
    - "alias stopn='sudo service nginx stop'"
    - "alias startn='sudo service nginx start'"
    - "alias m='mysql -h {{mysql_host}} -u {{mysql_username}} -p{{mysql_password}}'"
