---
#nginx_build_home: "/usr/local"
#nginx_home: "{{nginx_build_home}}/nginx"
nginx_home: "/etc/nginx"

# Settings for Jetty and Java. You probably won't have to alter these
# unles you are switching to a different version of Jetty or Java
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"

# Artifact Repositories
m2_repo_folder: "{{hosting_user_home}}/.m2/repository"
snapshot_repository_url: "https://nexus.hspconsortium.org/repository/maven-all/"
release_repository_url: "https://nexus.hspconsortium.org/repository/maven-all/"
smart_repo_base: "https://github.com/smart-on-fhir"
hspc_repo_base: "https://bitbucket.org/hspconsortium"
# By default Ansible will update the local copies of the servers code from
# the source repositories. Set this to "no" if you would rather not have the
# repositories updated on each run.
update_repositories: "yes"

# jetty_runner Artifact
jetty_runner_artifact_group_id: "org.eclipse.jetty"
jetty_runner_artifact_artifact_id: "jetty-runner"
jetty_runner_artifact_version: "9.3.6.v20151106"
jetty_runner_artifact_packaging: "jar"
jetty_runner_artifact_repository_url: "{{release_repository_url}}"
jetty_runner_artifact_location: "{{m2_repo_folder}}/org/hspconsortium/reference/{{api_server_artifact_artifact_id}}/{{api_server_artifact_version}}/{{api_server_artifact_artifact_id}}-{{api_server_artifact_version}}.{{api_server_artifact_packaging}}"

# Maximum size of sample patient data files
max_upload_size: "5M"

# database configuration
mysql_port: 3306
mysql_privilage: "*.*:ALL,GRANT"
mysql_connect_host: "%"
