---
- name: "drop the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{hosting_user_home}}/{{sandman_api_name}}"

- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/{{sandman_api_name}}"

- name: "download the app"
  become_user: "{{hosting_username}}"
  maven_artifact:
    group_id: "{{sandman_api_server_artifact_group_id}}"
    artifact_id: "{{sandman_api_server_artifact_artifact_id}}"
    version: "{{sandman_api_server_artifact_version}}"
    extension: "{{sandman_api_server_artifact_packaging}}"
    repository_url: "{{sandman_api_server_artifact_repository_url}}"
    dest: "{{hosting_user_home}}/{{sandman_api_name}}/{{sandman_api_server_artifact_artifact_id}}-{{sandman_api_server_artifact_version}}.{{sandman_api_server_artifact_packaging}}"

### SMART customization
- name: "create the smart directories"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/{{sandman_api_name}}/mysql"
    - "{{hosting_user_home}}/{{sandman_api_name}}/project/BOOT-INF/classes/db/mysql/migration"

- name: "process the templates"
  template:
    src: "{{item}}.j2"
    dest: "{{hosting_user_home}}/{{sandman_api_name}}/project/BOOT-INF/classes/db/mysql/migration/{{item}}"
    owner: "{{hosting_username}}"
    group: "{{hosting_username}}"
    mode: "0644"
  with_items:
    - "V9.1__Migrate_SMART_Logos.sql"
    - "V9.2__default_personas.sql"
    - "V9.3__remove_hspc_sandbox.sql"
    - "V9.4__default_apps.sql"
    - "V9.5__dstu2_sandbox.sql"
    - "V9.6__stu3_sandbox.sql"
    - "V10__remove_duplicate_user_sandboxes.sql"

- name: "update jar file"
  become_user: "{{hosting_username}}"
  shell: chdir={{hosting_user_home}}/{{sandman_api_name}}/project
        jar uf {{hosting_user_home}}/{{sandman_api_name}}/{{sandman_api_server_artifact_artifact_id}}-{{sandman_api_server_artifact_version}}.{{sandman_api_server_artifact_packaging}} {{item}}
  with_items:
    - "BOOT-INF/classes/db/mysql/migration/V9.1__Migrate_SMART_Logos.sql"
    - "BOOT-INF/classes/db/mysql/migration/V9.2__default_personas.sql"
    - "BOOT-INF/classes/db/mysql/migration/V9.3__remove_hspc_sandbox.sql"
    - "BOOT-INF/classes/db/mysql/migration/V9.4__default_apps.sql"
    - "BOOT-INF/classes/db/mysql/migration/V9.5__dstu2_sandbox.sql"
    - "BOOT-INF/classes/db/mysql/migration/V9.6__stu3_sandbox.sql"
    - "BOOT-INF/classes/db/mysql/migration/V10__remove_duplicate_user_sandboxes.sql"

- name: "install system"
  include: "roles/common-role/tasks/service_template.yml"
  vars:
    service_name: "{{sandman_api_name}}"
    database: "{{sandman_api_server_database}}"
    database_drop: "{{sandman_api_mysql_database_drop}}"
    database_exists: true
    service_definition_file: "{{common_service_template}}"
    service_start_command: "{{sandman_api_server_start_command}}"
    service_working_dir: "{{hosting_user_home}}/{{sandman_api_name}}"
    gateway_definition_file: "{{common_nginx_gateway_template}}"
    internal_port: "{{sandman_api_server_internal_port}}"
    external_host: "{{sandman_api_server_external_host}}"
    external_port: "{{sandman_api_server_external_port}}"
